services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: acme_csr_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - acme_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: acme_csr_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - acme_network
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: acme_csr_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-acme_csr}
      POSTGRES_USER: ${DB_USERNAME:-acme_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - acme_network

  redis:
    image: redis:7-alpine
    container_name: acme_csr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - acme_network

  node:
    image: node:20-alpine
    container_name: acme_csr_node
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - acme_network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  acme_network:
    driver: bridge

volumes:
  postgres_data: 